//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_472_PortfolioC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfEmployee
    {
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual EfDepartment EfDepartment { get; set; }
    }
}
